# Generated by Django 5.0.2 on 2025-01-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
