# Generated by Django 5.0.2 on 2025-01-29 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_level_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalLevelTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('picture_url', models.URLField(blank=True, null=True)),
                ('technical_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technicallevel')),
            ],
        ),
    ]
