# Generated by Django 5.0.2 on 2025-01-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_technicalleveltasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalleveltasks',
            name='category',
            field=models.CharField(choices=[('Forehand', 'Forehand'), ('Backhand', 'Backhand'), ('Serve', 'Serve'), ('Retur', 'Retur'), ('Volley', 'Volley'), ('Smash', 'Smash'), ('Forarbeid', 'Forarbeid')], default='Serve', max_length=10),
        ),
    ]
