# Generated by Django 5.0.2 on 2025-01-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_technicalleveltasks_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
