# Generated by Django 5.0.2 on 2025-01-30 14:53

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_level_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
