# Generated by Django 5.0.2 on 2025-01-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_level_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='short_desc',
            field=models.TextField(default=' '),
        ),
    ]
