# Generated by Django 5.0.2 on 2025-02-03 11:50

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_technicallevel_video_url_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicallevel',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
