# Generated by Django 5.0.2 on 2025-02-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_technicallevel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicallevel',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
