# Generated by Django 5.0.2 on 2025-02-03 13:41

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_technicallevel_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='picture_desc',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='technicalleveltasks',
            name='picture_desc',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
