# Generated by Django 5.0.2 on 2025-02-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_task_picture_desc_technicalleveltasks_picture_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(choices=[('Serve', 'Serve'), ('Retur', 'Retur'), ('Grunnspill', 'Grunnspill'), ('Volley', 'Volley'), ('Passering', 'Passering')], max_length=50),
        ),
    ]
