# Generated by Django 5.0.2 on 2025-02-06 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_task_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Mentalt', 'Mentalt'), ('Taktisk', 'Taktisk'), ('Fysisk', 'Fysisk')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='situation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.situationtype'),
        ),
    ]
