# Generated by Django 5.0.2 on 2025-02-06 10:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture_desc',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
