# Generated by Django 5.0.2 on 2025-02-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_task_situation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='coaching_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='doubles_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='need_to_travel_abroad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='level',
            name='number_of_tournaments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='other_sports_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='own_practice_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='physical_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='singles_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='weeks_of_holiday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='type_of_tournament',
            field=models.ManyToManyField(to='core.tournamenttype'),
        ),
    ]
