# Generated by Django 5.0.2 on 2025-02-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tournamenttype_level_coaching_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamenttype',
            name='short_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
