# Generated by Django 5.0.2 on 2025-02-14 13:37

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_technicallevel_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioChainPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Forehand', 'Forehand'), ('Backhand', 'Backhand'), ('Serve', 'Serve'), ('Retur', 'Retur'), ('Volley', 'Volley'), ('Smash', 'Smash'), ('Forarbeid', 'Forarbeid')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('diagnosis', tinymce.models.HTMLField()),
                ('diagnosis_video_url', models.URLField(blank=True, null=True)),
                ('diagnosis_picture_url', models.URLField(blank=True, null=True)),
                ('measure', tinymce.models.HTMLField()),
                ('measure_picture_url', models.URLField(blank=True, null=True)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.biochainpart')),
                ('technical_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.technicallevel')),
            ],
        ),
    ]
