# Generated by Django 5.0.2 on 2025-02-17 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_technicalpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalleveltasks',
            name='technical_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.technicalpart'),
        ),
    ]
