# Generated by Django 5.0.2 on 2025-02-17 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_diagnosis_technical_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='technical_level',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='technical_level_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.technicalleveltasks'),
        ),
    ]
