# Generated by Django 5.0.2 on 2025-02-17 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_diagnosis_technical_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='technical_level_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='core.technicalleveltasks'),
        ),
    ]
