# Generated by Django 5.0.2 on 2025-02-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_diagnosis_technical_level_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='category',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='technical_part',
        ),
    ]
