# Generated by Django 5.0.2 on 2025-02-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_trainingplan_drill_mentaltask_physicaltask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
    ]
