# Generated by Django 5.0.2 on 2025-02-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drill',
            name='task',
        ),
        migrations.RemoveField(
            model_name='drill',
            name='technical_level_task',
        ),
        migrations.AddField(
            model_name='drill',
            name='category',
            field=models.CharField(choices=[('Feeding', 'Feeding'), ('Semi-Live', 'Semi-Live'), ('Live', 'Live')], default='Feeding', max_length=20),
        ),
        migrations.AddField(
            model_name='drill',
            name='situation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drills', to='core.situationtype'),
        ),
        migrations.AddField(
            model_name='trainingplandrill',
            name='selected_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.level'),
        ),
        migrations.CreateModel(
            name='KeyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_points', to='core.drill')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_points', to='core.level')),
            ],
        ),
    ]
