# Generated by Django 5.0.2 on 2025-02-27 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_drill_task_remove_drill_technical_level_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='situation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drills', to='core.situationtype'),
        ),
        migrations.AlterField(
            model_name='trainingplandrill',
            name='selected_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.level'),
        ),
    ]
